### ISSUE TITLE
Line by Line coverage not seen 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [simplivity/bullshtml#22]
```
What steps will reproduce the problem?
1.Run a coverage using Bullseye 8.9.44 on Linux-x64
2. Parse xml output using: env PATH=$BULLSEYE_BIN:$PATH bullshtml/bullshtml 
bulls-html
3. Open the HTML using: google-chrome bulls-html/index.html


What is the expected output? What do you see instead?
Hyper links work all the way down to .c file. But when clicking the links to 
the function names, it does not take me to the source code. Coverage metrics 
like TF and ✓ are not seen next to the source code

Oddly, The links work for the first function in each c file. Even the TF and 
✓ are drawn as expected 

What version of the product are you using? On what operating system?
Bullseye 8.9.44 on Linux-x64
bullshtml 1.0.5 (tried 1.0.4 too)


Please provide any additional information below.


```

Original issue reported on code.google.com by `gagi...@gmail.com` on 21 May 2015 at 1:40

**Comment by RafalSkorka** [comment]
Hello Kevin, I do not see your changes, but I have created another fork of the original code here: https://github.com/RafalSkorka/bullshtml and I have fixed some issues there. I was not able to reproduce your issue, but if you could merge the changes to your fork I would be happy to take them also to my fork.

**Comment by kpease-svt** [comment]
Hi Rafal - sorry about that, I got sidetracked with a few issues here and our intended publication got delayed.

I'm actually in the process of rolling out our changes internally here at SimpliVity after a successful round of tests, and I'll be sending a push up with our changes in the next few days.

**Comment by RafalSkorka** [comment]
ok, thank you!
